### ISSUE TITLE
How do i compile the main.c in Linux ?

### ISSUE THREAD

**Issue by MalikSploit** [poupou9779/z2048#2]
I can't run this code on linux, do you know how i could run it using cmake, then make ?
or using : gcc -o jeu main.c  -lSDLmain -lSDL -lSDL_image -lSDL_ttf

**Comment by poupou9779** [comment]
cmake and make would be used to compile, not run the code. If you want to use either of these, you should write a `Makefile` or a `CMakeLists.txt` that are not included in this (very old) repository. If you want to compile on linux, install the SDL (verion 1, not 2) (`sudo dnf install SDL-devel` on Fedora) and then run something like `gcc src/*.c ./z2048 -lSDL` from the root of the repo.

This code was initially meant to only run on my local Win7, you might want to change `\\` by `/` in all the hardcoded paths for Linux compatibility though.
